const DataPenerbangan = [
  [
    "Bandung",
    "Lampung",
    "Jawa",
    "Ambon",
    "Aceh",
    "Jakarta",
    "Jambi",
    "Maluku",
    "Pontianak",
    "Samarinda",
  ],
  [
    "Lampung",
    "Bandung",
    "Ambon",
    "Jawa",
    "Samarinda",
    "Maluku",
    "Pontianak",
    "Jakarta",
    "Jambi",
    "Aceh",
  ],
  [
    "11 Desember 2022",
    "11 Desember 2022",
    "11 Desember 2022",
    "11 Desember 2022",
    "11 Desember 2022",
    "11 Desember 2022",
  ],
  [
    "Garuda Indonesia",
    "Lion Air",
    "Batik Air",
    "Garuda Indonesia",
    "Lion Air",
    "Batik Air",
    "Batik Air",
    "Garuda Indonesia",
    "Lion Air",
    "Batik Air",
  ],
];

export default DataPenerbangan;
